---
title: "figure_1"
author: "vb"
format: html
editor: visual
---

## Figure 1 - C2C12 C08

### functions and libraries

```{r}

#libraries
library(EBImage)
library(imager)
library(imagerExtra)
library(magick)

library(tidyverse)
library(pipeR)

#percentage_crop

#manual_crop

#get_intermediate_images

get_intermediate_images <- 
  function(path_name,
          crop_percentage = 0,
          my_isoblur = 1, 
          my_k = 0.01, 
          my_ws = 201,
          my_clean = 2,
          my_grow = 0, 
          my_shrink = 3){
  
  #from shiny app 
  
  results <- list()
  
  path_name %>% 
    EBImage::readImage() %>%
    percentage_crop(crop_percentage) %>% 
    magick::image_read() %>%
    imager::magick2cimg() %>%
    imager::grayscale() %>>% (~results$original = .) %>% 
    imager::isoblur(my_isoblur) %>>% (~results$isoblur = .) %>% 
    imagerExtra::ThresholdAdaptive(
      k = my_k, #0.1
      windowsize = my_ws, #39
      range = c(0,1)) %>>% (~results$adapThresh = . ) %>% 
    imager::clean(my_clean) %>>% (~results$clean = . ) %>% 
    imager::imgradient("xy") %>%
    imager::enorm() %>%
    imager::as.pixset() %>>% (~results$edge = . ) %>% 
    imager::grow(my_grow) %>>% (~results$grow = . ) %>%   
    imager::shrink(my_shrink) %>>% (~results$shrink = . )
  
  return(results)
}

```

### settings for C08

```{r}

my_crop_percentage <- 0.05
my_isoblur <- 1
my_k <- 0.1
my_ws <- 39
my_clean <-  0
my_grow <- 0
my_shrink <- 4

```

### no crop

```{r}
#| fig-width: 8.136
#| fig-height: 5.992

  results <- list()

  results <- 
    individual_filpath_C08_221207_BF %>%  
      get_intermediate_images(.,
        crop_percentage = my_crop_percentage,
        my_isoblur = my_isoblur,
        my_k = my_k, 
        my_ws = my_ws,
        my_clean = my_clean,
        my_grow = my_grow, 
        my_shrink = my_shrink) %>% 
      keep(names(.) %in% c("original",
                           "adapThresh",
                           "edge",
                           "shrink")) %>% 
      purrr::map(
        .x = .,
        .f = ~.x %>% 
          EBImage::Image() %>%  
          plot)
          
```

### manual crop

```{r}
#| fig-width: 8.285
#| fig-height: 7.1

  results <- list()

  results <- 
    individual_filpath_C08_221207_BF %>%  
      get_intermediate_images(.,
        crop_percentage = my_crop_percentage,
        my_isoblur = my_isoblur,
        my_k = my_k, 
        my_ws = my_ws,
        my_clean = my_clean,
        my_grow = my_grow, 
        my_shrink = my_shrink) %>% 
      keep(names(.) %in% c("original",
                           "adapThresh",
                           "edge",
                           "shrink")) %>% 
      purrr::map(
        .x = .,
        .f = ~.x %>% 
          EBImage::Image() %>%  
          manual_crop(crop_y_left = 0.84,
              crop_y_right = 0.03,
              crop_x_low = 0.84,
              crop_x_up = 0.01) %>% plot)
  
```
