---
title: "figure_4"
author: "vb"
format: html
editor: visual
---


## nuclei vs estimated cell number

### functions and library

```{r}

#libraries
library(tidyverse)


```

### set parameters and input

```{r}

#summarized_thp1
#summarized_c2c12
#summarized_a172
#summarized_a172_13
#summarized_a549
#summarized_a549_13


```

### THP1

```{r}
#| fig-width: 12
#| fig-height: 12

rho_thp1 <- cor.test(x=summarized_thp1$nuclei, 
         y=summarized_thp1$n, method = 'spearman') %>%  
  pluck("estimate") %>% unname()

label_rho <- paste0("R = ", round(rho_thp1, 3), ", p < 0.001")

summarized_thp1 %>% 
  filter(!str_detect(file, "E9")) %>% #E9 image is blurry
    ggplot(aes(x = nuclei, y = n))+
      geom_point(size = 10, alpha = 0.8, color = "darkgreen")+
      geom_abline(slope=1, intercept = 0, linetype = "dotted")+
      annotate(geom = "text",
               x = 100,
               y = 5000,
               label = label_rho,
               size = 12,
               hjust = 0)+
      annotate(geom = "text",
               x = 500,
               y = 100,
               label = "... = y ~ x",
               size = 12,
               hjust = 0,
               )+
      labs(subtitle = "THP1",
        x = "Number of nuclei",
           y = "Estimated number of cells")+
      lims(x = c(0, 5200),
           y = c(0, 5200))+
      theme_BF_larger() +
      theme(legend.position = "none")+
      theme(aspect.ratio = 1)




```

### C2C12

```{r}
#| fig-width: 12
#| fig-height: 12

rho_thp1 <- cor.test(x=summarized_c2c12$nuclei, 
         y=summarized_c2c12$n, method = 'spearman') %>%  
  pluck("estimate") %>% unname()

label_rho <- paste0("R = ", round(rho_thp1, 3), ", p < 0.001")

summarized_c2c12 %>% 
    ggplot(aes(x = nuclei, y = n))+
      geom_point(size = 10, alpha = 0.8, color = "darkgreen")+
      geom_abline(slope=1, intercept = 0, linetype = "dotted")+
      annotate(geom = "text",
               x = 100,
               y = 2000,
               label = label_rho,
               size = 12,
               hjust = 0)+
      annotate(geom = "text",
               x = 200,
               y = 100,
               label = "... = y ~ x",
               size = 12,
               hjust = 0,
               )+
      labs(subtitle = "C2C12",
            x = "Number of nuclei",
           y = "Estimated number of cells")+
      lims(x = c(0, 2100),
           y = c(0, 2100))+
      theme_BF_larger() +
      theme(legend.position = "none")+
      theme(aspect.ratio = 1)




```

### A172

```{r}
#| fig-width: 12
#| fig-height: 12

my_rho <- cor.test(x=summarized_a172 %>% 
                       filter(timepoint == 7) %>%  pluck("nuclei"), 
         y=summarized_a172 %>% filter(timepoint == 7) %>%  pluck("n"), 
         method = 'spearman') %>%  
  pluck("estimate") %>% unname()

label_rho <- paste0("R = ", round(my_rho, 3), ", p < 0.001")

summarized_a172 %>% 
  filter(timepoint == 7) %>% 
    ggplot(aes(x = nuclei, y = n))+
      geom_point(size = 10, alpha = 0.8, color = "darkgreen")+
      geom_abline(slope=1, intercept = 0, linetype = "dotted")+
      annotate(geom = "text",
               x = 20,
               y = 1100,
               label = label_rho,
               size = 12,
               hjust = 0)+
      annotate(geom = "text",
               x = 200,
               y = 100,
               label = "... = y ~ x",
               size = 12,
               hjust = 0,
               )+
      labs(subtitle = "A172 - 24h",
            x = "Number of nuclei",
           y = "Estimated number of cells")+
      lims(x = c(0, 1100),
             y = c(0, 1100))+
      theme_BF_larger() +
      theme(legend.position = "none")+
      theme(aspect.ratio = 1)



my_rho <- cor.test(x=summarized_a172_13 %>% 
                       filter(timepoint == 13) %>%  pluck("nuclei"), 
         y=summarized_a172_13 %>% filter(timepoint == 13) %>%  pluck("n"), 
         method = 'spearman') %>%  
  pluck("estimate") %>% unname()

label_rho <- paste0("R = ", round(my_rho, 3), ", p < 0.001")

summarized_a172_13 %>% 
  filter(timepoint == 13) %>% 
      ggplot(aes(x = nuclei, y = n))+
      geom_point(size = 10, alpha = 0.8, color = "darkgreen")+
      geom_abline(slope=1, intercept = 0, linetype = "dotted")+
      annotate(geom = "text",
               x = 20,
               y = 2100,
               label = label_rho,
               size = 12,
               hjust = 0)+
      annotate(geom = "text",
               x = 200,
               y = 100,
               label = "... = y ~ x",
               size = 12,
               hjust = 0,
               )+
      labs(subtitle = "A172 - 48h",
            x = "Number of nuclei",
           y = "Estimated number of cells")+
      lims(x = c(0, 2200),
             y = c(0, 2200))+
      theme_BF_larger() +
      theme(legend.position = "none")+
      theme(aspect.ratio = 1)

```

### A549

```{r}
#| fig-width: 12
#| fig-height: 12

my_rho <- cor.test(x=summarized_a549 %>% 
                       filter(timepoint == 7) %>%  pluck("nuclei"), 
         y=summarized_a549 %>% filter(timepoint == 7) %>%  pluck("n"), 
         method = 'spearman') %>%  
  pluck("estimate") %>% unname()

label_rho <- paste0("R = ", round(my_rho, 3), ", p < 0.001")

summarized_a549 %>% 
  filter(timepoint == 7) %>% 
  ggplot(aes(x = nuclei, y = n))+
      geom_point(size = 10, alpha = 0.8, color = "darkgreen")+
      geom_abline(slope=1, intercept = 0, linetype = "dotted")+
      annotate(geom = "text",
               x = 20,
               y = 800,
               label = label_rho,
               size = 12,
               hjust = 0)+
      annotate(geom = "text",
               x = 200,
               y = 100,
               label = "... = y ~ x",
               size = 12,
               hjust = 0,
               )+
      labs(subtitle = "A549 - 24h",
            x = "Number of nuclei",
           y = "Estimated number of cells")+
      # lims(x = c(0, 2200),
      #        y = c(0, 2200))+
      theme_BF_larger() +
      theme(legend.position = "none")+
      theme(aspect.ratio = 1)

my_rho <- cor.test(x=summarized_a549_13 %>% 
                       filter(timepoint == 13) %>%  pluck("nuclei"), 
         y=summarized_a549_13 %>% filter(timepoint == 13) %>%  pluck("n"), 
         method = 'spearman') %>%  
  pluck("estimate") %>% unname()

label_rho <- paste0("R = ", round(my_rho, 3), ", p < 0.001")


summarized_a549_13 %>% 
  filter(timepoint == 13) %>% 
  ggplot(aes(x = nuclei, y = n))+
      geom_point(size = 10, alpha = 0.8, color = "darkgreen")+
      geom_abline(slope=1, intercept = 0, linetype = "dotted")+
      annotate(geom = "text",
               x = 20,
               y = 2100,
               label = label_rho,
               size = 12,
               hjust = 0)+
      annotate(geom = "text",
               x = 200,
               y = 100,
               label = "... = y ~ x",
               size = 12,
               hjust = 0,
               )+
      labs(subtitle = "A549 - 48h",
            x = "Number of nuclei",
           y = "Estimated number of cells")+
      # lims(x = c(0, 2200),
      #        y = c(0, 2200))+
      theme_BF_larger() +
      theme(legend.position = "none")+
      theme(aspect.ratio = 1)

```
